# This is based on the Flux Container Tutorial
# See https://flux-framework.readthedocs.io/en/latest/tutorials/containers

x-shared-workers:
  &workers
  replicas: 4

x-shared-build-args: &shared-build-args
  flux_sched_version: jammy
  <<: *workers

x-shared-build-context: &shared-build-context
  context: ../..
  dockerfile: containers/spindle-flux-ubuntu/Dockerfile
  args: *shared-build-args
    
x-shared-environment: &shared-environment
  mainHost: node-1
  workdir: /code/workdir
  <<: *workers

x-shared-volumes: &shared-volumes
  - ./flux/imp.toml:/etc/flux/imp/conf.d/imp.toml
  - ./flux/broker.toml:/etc/flux/config/broker.toml
  - ./:/code/workdir
  - shared:/shared

volumes:
  shared:

networks:
  flux:
    driver: bridge

x-shared-node-parameters: &shared-node-parameters
  build: *shared-build-context
  networks:
    - flux
  environment: *shared-environment
  volumes: *shared-volumes
  cap_add:
    - SYS_NICE

services:
  node-1:
    <<: *shared-node-parameters
    hostname: node-1
    container_name: node-1
    healthcheck:
      test: ["CMD", "./flux_healthcheck.sh"]
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 5

  node-2:
    <<: *shared-node-parameters
    hostname: node-2      
    container_name: node-2

  node-3:
    <<: *shared-node-parameters
    hostname: node-3
    container_name: node-3

  node-4:
    <<: *shared-node-parameters
    hostname: node-4
    container_name: node-4

