services:
  spindle-slurm-base:
    image: ghcr.io/paratoolsinc/spindle-slurm-base:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UBUNTU_VERSION: noble
        SLURM_VERSION: slurm-25-05-3-1
        MPICH_VERSION: 4.2.2

