name: CI

on: [push, pull_request]

jobs:
  test-spindle:
    name: Test Spindle
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Check out commit to test
        uses: actions/checkout@v5
        with:
          path: 'Spindle'

      - name: Setup Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Log runner info
        id: info
        continue-on-error: true
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref:        ${{ github.ref }}"
          set -x
          docker --version
          docker compose version
          uname -a
          mount
          df -h
          getent passwd
          getent group
          ls -la
          ls -la ./Spindle

      - name: Build spindle-serial-ubuntu image
        id: serial-ubuntu-build
        run: |
          cd Spindle/containers/spindle-serial-ubuntu
          docker compose build --progress=plain

      - name: Bring spindle-serial-ubuntu up
        id: serial-ubuntu-up
        run: |
          cd Spindle/containers/spindle-serial-ubuntu
          docker compose up -d

      - name: Verify munge works in spindle-serial-ubuntu
        id: serial-ubuntu-munge
        run: |
          docker exec spindlenode bash -c 'munge -n | unmunge'

      - name: Run spindle-serial-ubuntu testsuite
        id: serial-ubuntu-testsuite
        run: |
          docker exec spindlenode bash -c 'cd Spindle-build/testsuite && ./runTests'

      - name: Bring spindle-serial-ubuntu down
        id: down-serial-ubuntu
        if: ${{ always() }}
        continue-on-error: true
        run: |
          cd Spindle/containers/spindle-serial-ubuntu
          docker compose down
